### ISSUE TITLE
With TLS and Without TLS examples might be misleading

### ISSUE THREAD

**Issue by mfriesenegger** [k3s-io/docs#124]
As this is about Private Registry Configuration, the https://github.com/k3s-io/docs/blob/main/docs/installation/private-registry.md#with-tls and https://github.com/k3s-io/docs/blob/main/docs/installation/private-registry.md#without-tls  examples might be misleading.  In particular,

```
mirrors:
  docker.io:
```

should be

```
mirrors:
  mycustomreg.com:
```

A reader may skip over the first mirrors example and use an example from either TLS section.  The result is an error `"PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"` that the image cannot be found.

**Comment by brandond** [comment]
I don't agree that either is wrong. They both show use of `mycustomreg.com:5000` as a **mirror endpoint** for docker.io, with the local registry using either http or https. If we changed that to what you are suggesting, that would be configuring mirror endpoints for `mycustomreg.com` instead of for docker.io.
