### ISSUE TITLE
Documentation doesn't give details on external database setup and permissions

### ISSUE THREAD

**Issue by sprior** [k3s-io/docs#187]
When I read the existing documentation at https://docs.k3s.io/datastore about setting up a High Availability External DB there isn't any detail about how the database should be created and what permissions the user provided to k3s needs to have.  I would suggest the Drupal database setup page as an excellent example of the details that should go into this documentation for both MySQL and PostgreSQL: https://www.drupal.org/docs/getting-started/installing-drupal/create-a-database#create-a-database-using-mysqlmariadb-commands

The requirements for k3s might actually be the exact same as for Drupal but I don't know that.  Details like collation order and character set should be provided and an example database creation command are very helpful.  Similarly providing a list of the specific permissions required for the database userid are also needed so the user doesn't end up assigning all permissions which has security implications.

Using the Drupal docs as a start an making any necessary modifications would be a great improvement to the k3s docs on the topic.

**Comment by dereknola** [comment]
Since there are a variety of ways to setup and configure the external databases K3s supports, we will not cover how to setup and configure them. As far as permissions, it is assumed that the user would need privileged access to most queries, as K3s will be directly managing the database it is pointed to. You could fine more info by looking thru the Kine repo https://github.com/k3s-io/kine/tree/master/pkg/drivers
